# Generated by Django 4.2.17 on 2024-12-27 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0002_participation"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_filename", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("feedback_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback_backend_project.participant",
                    ),
                ),
            ],
        ),
    ]
