# Generated by Django 4.2.17 on 2024-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0003_videofeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participation",
            name="completed_feedback",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="participant",
        ),
        migrations.AddField(
            model_name="participation",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participation",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
