# Generated by Django 4.2.17 on 2024-12-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0005_participation_completed_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
    ]
