# Generated by Django 4.2.17 on 2024-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback_backend_project",
            "0008_feedback_feedback_timestamp_feedback_participant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_number", models.CharField(max_length=10, unique=True)),
                ("password_hash", models.CharField(max_length=128)),
            ],
        ),
    ]



