# Generated by Django 4.2.17 on 2024-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0010_participation_participant_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="participant_number",
            field=models.CharField(default="UNSPEC", max_length=10, unique=True),
        ),
    ]
