# Generated by Django 4.2.17 on 2024-12-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0011_alter_participation_participant_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="participant_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="participation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant",
                to="feedback_backend_project.participation",
            ),
        ),
    ]
