# Generated by Django 4.2.17 on 2024-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback_backend_project", "0012_participant_participant_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="participant_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
