# Generated by Django 4.2.17 on 2024-12-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback_backend_project",
            "0014_participant_video_order_participant_video_progress",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="neurological_disorder_present",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="yips_severity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
